export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGNOUT = 'SIGNOUT';
export type AUTH_SUCCESS = typeof AUTH_SUCCESS;
export type AUTH_FAIL = typeof AUTH_FAIL;
export type SIGNOUT = typeof SIGNOUT;

export const ADD_GOAL_SUCCESS = 'ADD_GOAL_SUCCESS';
export const ADD_GOAL_FAIL = 'ADD_GOAL_FAIL';
export type ADD_GOAL_SUCCESS = typeof ADD_GOAL_SUCCESS;
export type ADD_GOAL_FAIL = typeof ADD_GOAL_FAIL;

export const FETCH_GOALS_SUCCESS = 'FETCH_GOALS_SUCCESS';
export const FETCH_GOALS_FAIL = 'FETCH_GOALS_FAIL';
export type FETCH_GOALS_SUCCESS = typeof FETCH_GOALS_SUCCESS;
export type FETCH_GOALS_FAIL = typeof FETCH_GOALS_FAIL;

export const COMPLETE_GOAL_SUCCESS = 'COMPLETE_GOAL_SUCCESS';
export const COMPLETE_GOAL_FAIL = 'COMPLETE_GOAL_FAIL';
export type COMPLETE_GOAL_SUCCESS = typeof COMPLETE_GOAL_SUCCESS;
export type COMPLETE_GOAL_FAIL = typeof COMPLETE_GOAL_FAIL;

export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAIL = 'DELETE_GOAL_FAIL';
export type DELETE_GOAL_SUCCESS = typeof DELETE_GOAL_SUCCESS;
export type DELETE_GOAL_FAIL = typeof DELETE_GOAL_FAIL;

export const CLEAR_COMPLETED_GOALS_SUCCESS = 'CLEAR_COMPLETED_GOALS_SUCCESS';
export const CLEAR_COMPLETED_GOALS = 'CLEAR_COMPLETED_GOALS';
export type CLEAR_COMPLETED_GOALS_SUCCESS = typeof CLEAR_COMPLETED_GOALS_SUCCESS;
export type CLEAR_COMPLETED_GOALS = typeof CLEAR_COMPLETED_GOALS;
