export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGNOUT = 'SIGNOUT';

export const ADD_GOAL = 'ADD_GOAL';
export const ADD_GOAL_SUCCESS = 'ADD_GOAL_SUCCESS';
export const ADD_GOAL_FAIL = 'ADD_GOAL_FAIL';

export const FETCH_GOALS = 'FETCH_GOALS';
export const FETCH_GOALS_SUCCESS = 'FETCH_GOALS_SUCCESS';
export const FETCH_GOALS_FAIL = 'FETCH_GOALS_FAIL';

export const COMPLETE_GOAL = 'COMPLETE_GOAL';
export const COMPLETE_GOAL_SUCCESS = 'COMPLETE_GOAL_SUCCESS';
export const COMPLETE_GOAL_FAIL = 'COMPLETE_GOAL_FAIL';

export const DELETE_GOAL = 'DELETE_GOAL';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAIL = 'DELETE_GOAL_FAIL';

export const CLEAR_COMPLETED_GOALS_SUCCESS = 'CLEAR_COMPLETED_GOALS_SUCCESS';
export const CLEAR_COMPLETED_GOALS_FAIL = 'CLEAR_COMPLETED_GOALS_FAIL';
export const CLEAR_COMPLETED_GOALS = 'CLEAR_COMPLETED_GOALS';
